locale: en
site_url: https://www.loganfarci.com/
display_url: loganfarci.com

media_folder: content/images/uploads
public_folder: /images/uploads

backend:
  name: git-gateway
  repo: lfarci/loganfarci.com
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload “{{path}}”"
    deleteMedia: "Delete “{{path}}”"

collections:
  - name: pages
    label: Pages
    label_singular: Page
    description: Specific content for each page of the website.
    format: json
    extension: json
    files:
      - label: Landing page
        name: "index"
        file: content/data/index.json
        fields:
          - { label: Picture, name: picture, widget: image }
          - { label: Name, name: name, widget: string }
          - { label: Role, name: role, widget: string }
          - { label: Description, name: description, widget: string }

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "_"