#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { isAbsolute, relative, resolve, join, sep } from "node:path";

const root = resolve(import.meta.dirname, "..");
const resume = join(root, "content", "resume");
const generatedRoot = join(root, "build");
const data = join(root, "content", "data");
const outputIndex = process.argv.indexOf("--output");
const outputArg = outputIndex === -1 ? "build/resume" : process.argv[outputIndex + 1];
if (!outputArg) throw new Error("--output requires a path");
const output = resolve(root, outputArg);
const outputRelativeToBuild = relative(generatedRoot, output);
if (outputRelativeToBuild.startsWith("..") || isAbsolute(outputRelativeToBuild)) {
    throw new Error("Output must be inside the generated build directory");
}
const outputRelativeToResume = relative(resume, output);
const parentPrefix = `..${sep}`;
const outputIsInsideResume =
    !outputRelativeToResume ||
    (!outputRelativeToResume.startsWith(parentPrefix) &&
        outputRelativeToResume !== ".." &&
        !isAbsolute(outputRelativeToResume));
const malformedParentPath = outputRelativeToResume.startsWith("..") && !outputRelativeToResume.startsWith(parentPrefix);
if (outputIsInsideResume || malformedParentPath) throw new Error("Output must be outside content/resume");
if (existsSync(output)) rmSync(output, { recursive: true });
mkdirSync(join(output, "sections"), { recursive: true });
mkdirSync(join(output, "generated"));

const read = (name) => JSON.parse(readFileSync(join(data, name), "utf8"));
const tex = (value) =>
    String(value)
        .replaceAll("\\", "\\textbackslash{}")
        .replaceAll("&", "\\&")
        .replaceAll("%", "\\%")
        .replaceAll("#", "\\#")
        .replaceAll("_", "\\_")
        .replaceAll("{", "\\{")
        .replaceAll("}", "\\}");
const yearRange = (start, end) => `${start.slice(0, 4)}--${end ? end.slice(0, 4) : "Present"}`;
const experiences = read("experiences.json");
const education = read("education.json");
const certifications = read("certifications.json");
const byTitle = Object.fromEntries(certifications.map((item) => [item.title, item]));
const required = [
    "Azure Developer Associate",
    "Professional Scrum Developer I",
    "GitHub Actions",
    "Azure Fundamentals",
    "GitHub Foundations",
];
const missing = required.filter((title) => !byTitle[title]);
if (missing.length) throw new Error(`Missing canonical certifications: ${missing.join(", ")}`);
const current = experiences[0];
const command = (name, value) => `\\newcommand{\\${name}}{${tex(value)}}`;
const facts = [
    "% Generated by scripts/build-resume.mjs; do not edit.",
    command("ExperienceCurrentTitle", current.name),
    command("ExperienceCompany", current.company.name),
    command("ExperienceCurrentDates", yearRange(current.start, current.end)),
    command("EducationName", education.name),
    command("EducationUniversity", education.University),
    command("EducationDates", education.details[1].replace("–", "--")),
    command("CertificationAzureDeveloper", byTitle["Azure Developer Associate"].title),
    command("CertificationAzureDate", byTitle["Azure Developer Associate"].date.slice(0, 4)),
    command("CertificationScrum", byTitle["Professional Scrum Developer I"].title),
    command("CertificationScrumDate", byTitle["Professional Scrum Developer I"].date.slice(0, 4)),
    command("CertificationGithubActions", byTitle["GitHub Actions"].title),
    command("CertificationGithubActionsDate", byTitle["GitHub Actions"].date.slice(0, 4)),
    command("CertificationFundamentalsDate", byTitle["Azure Fundamentals"].date.slice(0, 4)),
    command("CertificationGithubFoundationsDate", byTitle["GitHub Foundations"].date.slice(0, 4)),
    "",
].join("\n");
cpSync(join(resume, "resume.tex"), join(output, "resume.tex"));
for (const name of ["summary.tex", "experience.tex", "skills.tex", "education.tex", "certifications.tex"])
    cpSync(join(resume, "sections", name), join(output, "sections", name));
writeFileSync(join(output, "generated", "facts.tex"), facts);
execFileSync("tectonic", ["--chatter", "minimal", "--outdir", output, join(output, "resume.tex")], {
    stdio: "inherit",
});
execFileSync(process.execPath, [join(root, "scripts", "validate-resume.mjs"), join(output, "resume.pdf")], {
    stdio: "inherit",
});
