name: "Release to Azure"

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
  workflow_dispatch:

permissions:
  contents: read

env:
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.BLOB_NAME }}" \
            -backend-config="access_key=${{ secrets.ACCESS_KEY }}"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}" \
            -var="workload_name=lfarci" \
            -out=tfplan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan