name: "Deploy Azure Storage Account"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the target environment"
        required: false
        type: choice
        default: Production
        options:
          - Production
      resource_group_name:
        description: "Resource group name"
        required: false
        default: "management-rg"
        type: string
      location:
        description: "Azure region for the storage account"
        required: false
        default: "germanywestcentral"
        type: string
      workload:
        description: "Descriptive name for the workload"
        required: false
        default: "loganfarci"
        type: string
      container_name:
        description: "Container name"
        required: false
        default: "terraformstate"
        type: string

permissions:
  id-token: write
  contents: read

env:
  STORAGE_ACCOUNT_NAME: "${{ github.event.inputs.workload }}${{ github.run_id }}"

jobs:
  deploy:
    name: "Deploy storage account"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create ${{ env.STORAGE_ACCOUNT_NAME }} storage account and ${{ github.event.inputs.container_name }} container
        run: .github/scripts/deploy_storage_account.sh
        env:
          RESOURCE_GROUP: ${{ github.event.inputs.resource_group_name }}
          LOCATION: ${{ github.event.inputs.location }}
          STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME }}"
          CONTAINER_NAME: "${{ github.event.inputs.container_name }}"