name: "Deploy Next Application"

on:
  push:
    branches:
      - main
    paths:
      - "!infra/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy Next Application"
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: output
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"