name: "Manage Azure Storage Account"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action to perform"
        required: true
        type: choice
        options:
          - Deploy
          - Destroy
      environment:
        description: "Select the target environment"
        required: false
        type: choice
        default: Production
        options:
          - Production
      resource_group_name:
        description: "Resource group name"
        required: false
        default: "management-rg"
        type: string
      location:
        description: "Azure region for the storage account"
        required: false
        default: "germanywestcentral"
        type: string
      storage_account_name:
        description: "Descriptive name for the storage account name"
        required: false
        default: "loganfarci"
        type: string
      container_name:
        description: "Container name"
        required: false
        default: "terraformstate"
        type: string

permissions:
  id-token: write
  contents: read

env:
  STORAGE_ACCOUNT_NAME: "${{ github.event.inputs.workload }}${{ github.run_id }}"

jobs:
  run:
    name: "Run storage account script"
    if: ${{ github.event.inputs.action == 'Deploy' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create ${{ github.event.inputs.storage_account_name }} storage account and ${{ github.event.inputs.container_name }} container
        run: .github/scripts/deploy_storage_account.sh
        env:
          RESOURCE_GROUP: ${{ github.event.inputs.resource_group_name }}
          LOCATION: ${{ github.event.inputs.location }}
          STORAGE_ACCOUNT_NAME: "${{ github.event.inputs.storage_account_name }}"
          CONTAINER_NAME: "${{ github.event.inputs.container_name }}"
          DESTROY: ${{ github.event.inputs.action == 'Destroy' }}