name: "Manage Management Key Vault"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action to perform"
        required: true
        type: choice
        options:
          - Deploy
          - Destroy
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - Production
      resource_group_name:
        description: "Resource group name"
        required: false
        default: "management-rg"
        type: string
      location:
        description: "Location"
        required: false
        default: "germanywestcentral"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run:
    name: "Run Key Vault script"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate key vault name
        id: generate_key_vault_name
        run: |
          name=$(echo -n "${GITHUB_REPOSITORY}-${GITHUB_RUN_ID}" | sha256sum | cut -c1-8)kv
          echo "key_vault_name=${name}" >> $GITHUB_OUTPUT

      - name: Create ${{ steps.generate_key_vault_name.outputs.key_vault_name }} key vault
        run: .github/scripts/key_vault.sh
        env:
          RESOURCE_GROUP_NAME: "${{ github.event.inputs.resource_group_name }}"
          LOCATION: "${{ github.event.inputs.location }}"
          KEY_VAULT_NAME: "${{ steps.generate_key_vault_name.outputs.key_vault_name }}"
          DESTROY: ${{ github.event.inputs.action == 'Destroy' }}