name: "Manage Terraform State Storage Account"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action to perform"
        required: true
        type: choice
        options:
          - Deploy
          - Destroy
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - Production
      resource_group_name:
        description: "Resource group name"
        required: false
        default: "management-rg"
        type: string
      location:
        description: "Location"
        required: false
        default: "germanywestcentral"
        type: string
      storage_account_name:
        description: "Storage account name"
        required: false
        default: "loganfarci"
        type: string
      container_name:
        description: "Container name"
        required: false
        default: "terraformstate"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run:
    name: "Run storage account script"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create ${{ github.event.inputs.storage_account_name }} storage account and ${{ github.event.inputs.container_name }} container
        run: .github/scripts/storage_account.sh
        env:
          RESOURCE_GROUP: ${{ github.event.inputs.resource_group_name }}
          LOCATION: ${{ github.event.inputs.location }}
          STORAGE_ACCOUNT_NAME: "${{ github.event.inputs.storage_account_name }}"
          CONTAINER_NAME: "${{ github.event.inputs.container_name }}"
          DESTROY: ${{ github.event.inputs.action == 'Destroy' }}

      - name: Get storage account key
        id: get_key
        run: |
          key=$(az storage account keys list --account-name "${{ github.event.inputs.storage_account_name }}" --query "[0].value" -o tsv)
          echo "key=$key" >> $GITHUB_OUTPUT

      - name: Set secrets in Key Vault
        run: |
          az keyvault secret set --vault-name ${{ secrets.AZURE_KEY_VAULT_NAME }} --name "TerraformBackendResourceGroup" --value "${{ github.event.inputs.resource_group_name }}"
          az keyvault secret set --vault-name ${{ secrets.AZURE_KEY_VAULT_NAME }} --name "TerraformBackendStorageAccountName" --value "${{ github.event.inputs.storage_account_name }}"
          az keyvault secret set --vault-name ${{ secrets.AZURE_KEY_VAULT_NAME }} --name "TerraformBackendContainerName" --value "${{ github.event.inputs.container_name }}"